server:
  port: 9000
ignore:
  clients:
  - app
ribbon:
  ReadTimeout: 700000000
  SocketTimeout: 700000000
  NFLoadBalancerPingInterval: 3
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9000/uniform/uac/oauth/token
      clientId: webApp
      clientSecret: 123456
      user-authorization-uri: http://localhost:9000/uniform/uac/oauth/authorize
    resource:
      user-info-uri: http://localhost:9000/uniform/uac/user
  validate:
    code: true
    privateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEApivUg4CsOHsZX09HhfUthRuae3xNDV6D3U36acu0JUd9efbgtHME89B5jqD4ZGowKobLqms/TksDutfFz5z0AQIDAQABAkB0gfqokQkvOLAbcTyWocbesvHnbsmffAs8mTXgA6E1GPqGDOfWnPnmG34KVVj0xDb7juLR32m7TlJYiRjxIhJZAiEA+LBhnjuJkSBEpaOYx0+nCTF6KJwwLrT8p+wPBKq6SpMCIQCrDmzErPch9L5E8Bry1pST6i+ZossBpxbQofBE004fmwIgZNHU8Xo/nidPzTsSsBLZq/9z/8y6N+VF3Kn1uLWiSqMCIQCmFOBYaROd3XIrnvCbXOpvXw6OXfg7B49oTALr4DnXBwIgGWMqDalv/D4yHsI9FddMBBVqfKkVHNINMoGFle+KdYo=
    useRSA: true
spring:
  application:
    name: @pom.artifactId@
  rabbitmq:
    host: 10.10.1.79
    password: guest
    port: 5672
    username: guest
  redis:
    host: 10.10.1.79
    password: 123456
    port: 6379
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  ratelimit:
    behind-proxy: false
    default-policy:
      limit: 300
      quota: 1000
      refresh-interval: 60
      type: origin
    enabled: true
    key-prefix: sloth-ratelimit
    policies:
      sloth-provider-uac:
        limit: 300
        quota: 1000
        refresh-interval: 60
        type: origin
    repository: redis
  routes:
    complain:
      id: sloth-provider-complaints
      path: /complaint/**
      service-id: sloth-provider-complaints
    order:
      id: sloth-provider-order
      path: /order/**
      service-id: sloth-provider-order
    product:
      id: product
      path: /product/**
      service-id: product
    uac:
      id: sloth-provider-uac
      path: /uac/**
      service-id: sloth-provider-uac
    backstage:
      id: ds-backstage
      path: /backstage/**
      service-id: ds-backstage
    supplychain:
      id: supplychain
      path: /supplychain/**
      service-id: supplychain
    supplychain-backstage:
      id: supplychain-backstage
      path: /supplychain-backstage/**
      service-id: supplychain-backstage
    audit:
      id: audit
      path: /audit/**
      service-id: audit
    ds-app-test:
      id: ds-app-test
      path: /ds-app-test/**
      service-id: ds-app-test
  sensitive-headers: ''

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
