server:
  port: 9005
spring:
  application:
    name: microserver-consumer-by-ribbon
  redis:
    host: 10.10.1.205
    password: 123456
    port: 6379
security: 
  oauth2:
    #client:
      #指定获取access token的URI.
      #access-token-uri: http://localhost:9000/uniform/uac/oauth/token
      #指定OAuth2 client ID.
      clientId: webApp
      clientSecret: 123456
      #用户跳转去获取access token的URI
      #user-authorization-uri: http://localhost:9000/uniform/uac/oauth/authorize
    resource:
      user-info-uri: http://localhost:9000/uniform/uac/user
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    #不注册eureka
    register-with-eureka: true
    #拉取注册清单
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/