server:
  port: 9002
spring:
  application:
    name: microserver-provider
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/