server:
  port: 9013
spring:
  application:
    name: single-config-client
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 10.10.1.69:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


username: dongss
